[root] # reserved

properties = [
	".sub_entry_types text = show",
]


[show]

environs = [
	"SHOW entry_name = .",
]

properties = [
	".sub_entry_types text = category",
	"sup user",
	"pd user",
	"pm user",
]

sub_entries = [
	'shot category = {"properties": {".sub_entry_types":"shot_group"}}',
	'asset category = {"properties": {".sub_entry_types":"asset_group"}}',
]


[category]

properties = [
	".sub_entry_types text = group",
]


[shot_group]

environs = [
	"GROUP entry_name = ."
]

properties = [
	".sub_entry_types text = shot"
]


[asset_group]

environs = [
	"GROUP entry_name = ."
]

properties = [
	".sub_entry_types text = asset"
]


[shot]

environs = [
	"UNIT entry_name = .",
]

properties = [
	".sub_entry_types text = part",
	"status text",
	"cg text",
	"direction text",
	"note text",
	"tc_in timecode",
	"tc_out timecode",
	"difficulty int",
	"priority int",
	"due date",
]

sub_entries = [
]


[asset]

environs = [
	"UNIT entry_name = .",
]

properties = [
	".sub_entry_types text = part",
	"status text",
	"cg text",
	"direction text",
	"note text",
	"difficulty int",
	"priority int",
	"due date",
]

sub_entries = [
	"mod part",
]


[part]

environs = [
	"PART entry_name = .",
]

properties = [
	".sub_entry_types text = elem",
]

sub_entries = [
	"main elem",
]


[elem]

environs = [
	"ELEM entry_name = .",
]

properties = [
	".sub_entry_types text = ver",
	"note text",
]

sub_entries = [
	"v001 ver",
]


[ver]

environs = [
	"VER entry_name = .",
]

properties = [
	"confirm text",
	"note text",
]
