[[types]]

name = "root"

properties = [
	".sub_entry_types text = show",
]


[[types]]

name = "show"

environs = [
	"SHOW entry_name = .",
]

properties = [
	".sub_entry_types text = category",
	"sup user",
	"pd user",
	"pm user",
]

sub_entries = [
	'shot category.shot',
	'asset category.asset',
]


[[types]]

name = "category"

properties = [
	".sub_entry_types text = group",
]

[[types]]

name = "category.shot"

properties = [
	".predefined_sub_entries text = *:group.shot",
]

[[types]]

name = "category.asset"

properties = [
	".predefined_sub_entries text = *:group.asset",
]


[[types]]

name = "group"

environs = [
	"GROUP entry_name = ."
]


[[types]]

name = "group.shot"

properties = [
	".sub_entry_types text = shot"
]


[[types]]

name = "group.asset"

properties = [
	".sub_entry_types text = asset"
]


[[types]]

name = "shot"

environs = [
	"UNIT entry_name = .",
]

properties = [
	".sub_entry_types text = part",
	"status text",
	"cg text",
	"direction text",
	"note text",
	"tc_in timecode",
	"tc_out timecode",
	"difficulty int",
	"priority int",
	"due date",
]

sub_entries = [
]


[[types]]

name = "asset"

environs = [
	"UNIT entry_name = .",
]

properties = [
	".sub_entry_types text = part",
	"status text",
	"cg text",
	"direction text",
	"note text",
	"difficulty int",
	"priority int",
	"due date",
]

sub_entries = [
	"mod part",
]


[[types]]

name = "part"

environs = [
	"PART entry_name = .",
]

properties = [
	".sub_entry_types text = elem",
]

sub_entries = [
	"main elem",
]


[[types]]

name = "elem"

environs = [
	"ELEM entry_name = .",
]

properties = [
	".sub_entry_types text = ver",
	"note text",
]

sub_entries = [
	"v001 ver",
]


[[types]]

name = "ver"

environs = [
	"VER entry_name = .",
]

properties = [
	"confirm text",
	"note text",
]
