[root] # reserved

sub_entry_types = [
	"show",
]


[show]

environs = [
	"SHOW entry_name=.",
]

properties = [
	"sup user",
	"pd user",
	"pm user",
]

sub_entry_types = [
	"shotgrp",
	"assetgrp",
]

sub_entries = [
	"shot shotgrp",
	"asset assetgrp",
]


[shotgrp]

environs = [
	"GROUP entry_name=."
]

sub_entry_types = [
	"shot",
]


[shot]

environs = [
	"UNIT entry_name=.",
]

properties = [
	"status text",
	"cg text",
	"direction text",
	"note text",
	"tc_in timecode",
	"tc_out timecode",
	"difficulty text",
	"priority int",
	"due date",
]

sub_entry_types = [
	"part",
]

sub_entries = [
	"comp part",
]


[assetgrp]

environs = [
	"GROUP entry_name=."
]

sub_entry_types = [
	"asset",
]

[asset]

environs = [
	"UNIT entry_name=.",
]

properties = [
	"status text",
	"cg text",
	"direction text",
	"note text",
	"difficulty text",
	"priority int",
	"due date",
]

sub_entry_types = [
	"part",
]

sub_entries = [
	"mod part",
]


[part]

environs = [
	"PART entry_name=.",
]

properties = [
]

sub_entry_types = [
	"elem",
]

sub_entries = [
	"main elem",
]


[elem]

environs = [
	"ELEM entry_name=.",
]

properties = [
	"note text",
]

sub_entry_types = [
	"ver",
]

sub_entries = [
	"v001 ver",
]


[ver]

environs = [
	"VER entry_name=.",
]

properties = [
	"confirm text",
	"note text",
]
