[root] # reserved

sub_entry_types = [
	"show",
]


[show]

environs = [
	"SHOW text={{.Name}}",
]

properties = [
	"sup user",
	"pd user",
	"pm user",
	"note text",
]

sub_entry_types = [
	"group",
]


[group]

environs = [
	"GROUP text={{.Name}}",
]

properties = [
	"note text",
]

sub_entry_types = [
	"unit",
]


[unit]

environs = [
	"UNIT text={{.Name}}",
]

properties = [
	"confirm text",
	"note text",
]

sub_entry_types = [
	"part",
]


[part]

environs = [
	"PART text={{.Name}}",
]

properties = [
	"note text",
]

sub_entry_types = [
	"elem",
]


[elem]

environs = [
	"ELEM text={{.Name}}",
]

properties = [
	"note text",
]

sub_entry_types = [
	"ver",
]


[ver]

environs = [
	"VER text={{.Name}}",
]

properties = [
	"confirm text",
	"note text",
]
