[root] # reserved

sub_entry_types = [
	"show",
]


[show]

environs = [
	"SHOW entry_name=.",
]

properties = [
	"sup user",
	"pd user",
	"pm user",
	"note text",
]

sub_entry_types = [
	"group",
]


[group]

environs = [
	"GROUP entry_name=.",
]

properties = [
	"note text",
]

sub_entry_types = [
	"unit",
]


[unit]

environs = [
	"UNIT entry_name=.",
]

properties = [
	"cg text",
	"direction text",
	"in timecode",
	"out timecode",
	"note text",
]

sub_entry_types = [
	"part",
]


[part]

environs = [
	"PART entry_name=.",
]

properties = [
	"confirm text",
]

sub_entry_types = [
	"elem",
]


[elem]

environs = [
	"ELEM entry_name=.",
]

properties = [
	"note text",
]

sub_entry_types = [
	"ver",
]


[ver]

environs = [
	"VER entry_name=.",
]

properties = [
	"confirm text",
	"note text",
]
